[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.111.3"
  HUGO_ENV = "production"


[[redirects]]
  from = "https://nwj.cc/*"
  to = "https://nwj.sh/:splat"
  status = 301
  force = true